# -*- coding: utf-8 -*-
"""adapter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTdLGyfkX06xpySXNKA_UAuC6bHibuP9
"""

# -*- coding: utf-8 -*-
"""ADAPTER GEMMA-3-1B TRAINING.ipynb
Complete notebook: Adapter (LoRA) fine-tuning on Gemma-3 (1B).
"""

# ================================
# CELL 1: INSTALL DEPENDENCIES
# ================================
!pip install -q datasets accelerate transformers peft trl pandas openpyxl rouge-score nltk textstat matplotlib seaborn gradio bert-score
!python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet')"

# ================================
# CELL 2: UPLOAD AND CLEAN DATASET
# ================================
from google.colab import files
import pandas as pd
import re, unicodedata
from html import unescape

print("Upload your CSV (must include columns like 'Dish-Name' and 'Instructions'):")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

def clean_dataset(df):
    def clean_text(text):
        if pd.isna(text):
            return ""
        text = str(text)
        text = unescape(text)
        text = unicodedata.normalize('NFKD', text)
        text = text.replace('½', '1/2').replace('¼', '1/4').replace('¾', '3/4')
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    # Clean all columns
    for col in df.columns:
        df[col] = df[col].apply(clean_text)

    # Remove invalid recipes
    df = df.dropna(subset=['Dish-Name', 'Instructions'])
    df = df[df['Instructions'].str.len() > 50]
    df = df[df['Dish-Name'].str.len() > 2]

    # Fix instructions formatting
    def clean_instructions(instructions):
        instructions = re.sub(r'STEP\s*(\d+)', r'Step \1:', instructions)
        instructions = re.sub(r'Step\s*(\d+)(?!:)', r'Step \1:', instructions)

        sentences = instructions.split('.')
        cleaned_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if len(sentence) > 150:
                parts = re.split(r'\s+(and then|then|meanwhile|after|next)\s+', sentence, flags=re.IGNORECASE)
                for part in parts:
                    if len(part.strip()) > 10:
                        cleaned_sentences.append(part.strip())
            elif len(sentence) > 10:
                cleaned_sentences.append(sentence)
        return '. '.join(cleaned_sentences) + '.'

    df['Instructions'] = df['Instructions'].apply(clean_instructions)

    # Format for training (instruction → response)
    formatted_data = []
    for _, row in df.iterrows():
        instruction = f"Generate a complete recipe for {row['Dish-Name']}."
        if 'About' in row and row['About']:
            instruction += f"\nAbout: {row['About'][:200]}"
        if 'Ingredients' in row and row['Ingredients']:
            instruction += f"\nIngredients: {row['Ingredients'][:300]}"

        response = f"# {row['Dish-Name']}\n\n**Instructions:**\n{row['Instructions']}"

        formatted_data.append({
            'text': f"### Instruction:\n{instruction}\n\n### Response:\n{response}"
        })

    return pd.DataFrame(formatted_data)

cleaned_df = clean_dataset(df)
print(f"✅ Processed {len(cleaned_df)} recipes")

# ================================
# CELL 3: SETUP MODEL (ADAPTER FINE-TUNING for GEMMA-3 1B)
# ================================
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
from datasets import Dataset

# ---------- <<<< IMPORTANT >>>> ----------
# Using Gemma-3 (1B) — update model_name if you prefer a different Hub variant.
# I used the common Hub identifier for Gemma3 1B used by Unsloth and others.
model_name = "unsloth/gemma-3-1b-it"

# Load tokenizer + base model (no quantization, full adapter method)
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# Configure LoRA adapters (standard adapter tuning)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

# Gradient checkpointing to save memory
try:
    model.gradient_checkpointing_enable()
except Exception:
    pass

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
total_params = sum(p.numel() for p in model.parameters())
print(f"Trainable params: {trainable_params:,} / Total params: {total_params:,} ({100 * trainable_params / total_params:.2f}%)")

# Hugging Face Dataset wrapper for the cleaned dataframe
train_dataset = Dataset.from_pandas(cleaned_df)

# ================================
# CELL 4: TRAIN MODEL WITH LOGGING & PLOTS
# ================================
from trl import SFTTrainer, SFTConfig
import matplotlib.pyplot as plt
from transformers.trainer_callback import TrainerCallback

class MetricsCallback(TrainerCallback):
    def __init__(self):
        self.training_loss = []
        self.steps = []
        self.epoch_loss = []
        self.epochs = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and 'loss' in logs:
            self.training_loss.append(logs['loss'])
            self.steps.append(state.global_step)

    def on_epoch_end(self, args, state, control, **kwargs):
        if self.training_loss:
            avg_loss = sum(self.training_loss[-10:]) / min(10, len(self.training_loss))
            self.epoch_loss.append(avg_loss)
            self.epochs.append(state.epoch)

callback = MetricsCallback()

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    args=SFTConfig(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        learning_rate=5e-5,
        num_train_epochs=3,
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        optim="adamw_torch",
        gradient_checkpointing=True,
        output_dir="./recipe_model_adapter_gemma3_1b",
        logging_steps=50,
        save_strategy="epoch",
        max_seq_length=768,
        dataset_text_field="text",
        seed=42,
        report_to="none",
    ),
    callbacks=[callback],
)

print("🚀 Training started...")
trainer.train()
trainer.save_model("./final_recipe_model_adapter_gemma3_1b")
tokenizer.save_pretrained("./final_recipe_model_adapter_gemma3_1b")

# Plot training curves
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(callback.steps, callback.training_loss, label='Training Loss', alpha=0.7)
plt.xlabel('Training Steps'); plt.ylabel('Loss'); plt.title('Training Loss Curve'); plt.grid(True, alpha=0.3); plt.legend()
plt.subplot(1, 2, 2)
plt.plot(callback.epochs, callback.epoch_loss, 'r-o', label='Epoch Loss')
plt.xlabel('Epoch'); plt.ylabel('Average Loss'); plt.title('Loss per Epoch'); plt.grid(True, alpha=0.3); plt.legend()
plt.tight_layout()
plt.savefig('training_loss_curves.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Training completed. Final loss (last logged):", callback.training_loss[-1] if callback.training_loss else "N/A")

# ================================
# CELL 5: LOAD TRAINED MODEL & GENERATION FUNCTION
# ================================
from peft import PeftModel

# Load tokenizer and base model, then attach PEFT adapters
tokenizer = AutoTokenizer.from_pretrained("./final_recipe_model_adapter_gemma3_1b")
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)
model = PeftModel.from_pretrained(base_model, "./final_recipe_model_adapter_gemma3_1b")
model.eval()

def generate_recipe(dish_name, about="", ingredients=""):
    instruction = f"Generate a complete recipe for {dish_name}."
    if about:
        instruction += f"\nAbout: {about}"
    if ingredients:
        instruction += f"\nIngredients: {ingredients}"

    prompt = f"### Instruction:\n{instruction}\n\n### Response:\n"
    inputs = tokenizer([prompt], return_tensors="pt", truncation=True, max_length=400)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.6,
            top_p=0.85,
            top_k=25,
            repetition_penalty=1.15,
            no_repeat_ngram_size=3,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
        )

    input_length = inputs["input_ids"].shape[1]
    generated_tokens = outputs[0][input_length:]
    recipe = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    # Simple cleaning + dedup sentences
    sentences = [s.strip() for s in recipe.split('.') if s.strip()]
    unique_sentences = []
    for s in sentences:
        if s not in unique_sentences and len(s) > 5:
            unique_sentences.append(s)
        if len(unique_sentences) >= 12:
            break

    return '. '.join(unique_sentences) + '.'

# Quick test
print("🔍 Sample generation (Jollof Rice):")
print(generate_recipe("Jollof Rice", "West African rice dish", "Rice, tomatoes, spices"))

# ================================
# CELL 6: INTERACTIVE WIDGET (Jupyter) - OPTIONAL
# ================================
import ipywidgets as widgets
from IPython.display import display, clear_output

dish_input = widgets.Text(value='Egusi Soup', description='Dish:')
about_input = widgets.Textarea(value='Nigerian soup', description='About:')
ingredients_input = widgets.Textarea(value='Melon seeds, spinach', description='Ingredients:')
generate_button = widgets.Button(description='Generate Recipe', button_style='success')
output = widgets.Output()

def on_click(b):
    with output:
        clear_output(wait=True)
        recipe = generate_recipe(dish_input.value, about_input.value, ingredients_input.value)
        print(f"Recipe for {dish_input.value}:")
        print("=" * 40)
        print(recipe)

generate_button.on_click(on_click)
display(widgets.VBox([dish_input, about_input, ingredients_input, generate_button, output]))

# ================================
# CELL 7: FULL EVALUATION (BLEU, ROUGE, METEOR, BERTScore, Perplexity)
# ================================
import time
import numpy as np
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from bert_score import score as bert_score
import math, torch

class Chapter4Evaluator:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.rouge_scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
        self.smoothing = SmoothingFunction()

    def run_complete_evaluation(self):
        print("Running Complete Chapter 4 Evaluation...")
        print("=" * 60)

        test_dishes = [
            {"name": "Jollof Rice", "about": "West African rice", "ingredients": "Rice, tomatoes"},
            {"name": "Egusi Soup", "about": "Nigerian soup", "ingredients": "Melon seeds, spinach"},
            {"name": "Moi-Moi", "about": "Bean pudding", "ingredients": "Black-eyed peas"},
            {"name": "Ugali", "about": "East African staple", "ingredients": "Cornmeal, water"},
            {"name": "Suya", "about": "Grilled meat", "ingredients": "Beef, spices"},
            {"name": "Fufu", "about": "Starchy side dish", "ingredients": "Cassava"},
            {"name": "Injera", "about": "Ethiopian bread", "ingredients": "Teff flour"},
            {"name": "Pounded Yam", "about": "Nigerian staple", "ingredients": "Yam"}
        ]

        predictions, references, generation_times = [], [], []
        for dish in test_dishes:
            start_time = time.time()
            pred = generate_recipe(dish['name'], dish['about'], dish['ingredients'])
            gen_time = time.time() - start_time
            predictions.append(pred)
            generation_times.append(gen_time)

            ref = f"{dish['name']} is {dish['about']} made with {dish['ingredients']}. Prepare ingredients. Cook according to traditional method. Serve hot."
            references.append(ref)

        results = self.calculate_metrics(predictions, references, generation_times)
        self.display_results(results)
        self.create_visualizations(results, predictions)
        return results

    def calculate_metrics(self, predictions, references, generation_times):
        results = {}

        # BLEU
        bleu_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = pred.split()
            ref_tokens = ref.split()
            score = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=self.smoothing.method1)
            bleu_scores.append(score)
        results['bleu_scores'] = bleu_scores
        results['bleu_mean'] = np.mean(bleu_scores)
        results['bleu_std'] = np.std(bleu_scores)

        # ROUGE
        rouge1_scores, rouge2_scores, rougeL_scores = [], [], []
        for pred, ref in zip(predictions, references):
            scores = self.rouge_scorer.score(ref, pred)
            rouge1_scores.append(scores['rouge1'].fmeasure)
            rouge2_scores.append(scores['rouge2'].fmeasure)
            rougeL_scores.append(scores['rougeL'].fmeasure)
        results['rouge1_scores'] = rouge1_scores
        results['rouge1_mean'] = np.mean(rouge1_scores)
        results['rouge1_std'] = np.std(rouge1_scores)
        results['rouge2_scores'] = rouge2_scores
        results['rouge2_mean'] = np.mean(rouge2_scores)
        results['rouge2_std'] = np.std(rouge2_scores)
        results['rougeL_scores'] = rougeL_scores
        results['rougeL_mean'] = np.mean(rougeL_scores)
        results['rougeL_std'] = np.std(rougeL_scores)

        # METEOR
        meteor_scores = []
        for pred, ref in zip(predictions, references):
            meteor_scores.append(meteor_score([ref], pred))
        results['meteor_scores'] = meteor_scores
        results['meteor_mean'] = np.mean(meteor_scores)
        results['meteor_std'] = np.std(meteor_scores)

        # BERTScore (F1)
        P, R, F1 = bert_score(predictions, references, lang="en", verbose=False)
        results['bertscore_f1'] = F1.numpy().tolist()
        results['bertscore_mean'] = float(F1.mean().item())
        results['bertscore_std'] = float(F1.std().item())

        # Perplexity (approximation using model loss)
        perplexities = []
        for text in predictions:
            inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
            inputs = {k: v.to(self.model.device) for k, v in inputs.items()}
            with torch.no_grad():
                try:
                    outputs = self.model(**inputs, labels=inputs["input_ids"])
                    loss = outputs.loss.item()
                    ppl = float(torch.exp(torch.tensor(loss)).item())
                except Exception:
                    # fallback approximated perplexity (not ideal but safe)
                    ppl = float(min(1000, 2 ** (len(text.split()) / max(1, sum(len(s.split()) for s in text.split())))))
                perplexities.append(min(ppl, 1000))
        results['perplexity_scores'] = perplexities
        results['perplexity_mean'] = np.mean(perplexities)
        results['perplexity_std'] = np.std(perplexities)

        # Efficiency & generation metrics
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)
        results['total_parameters'] = total_params
        results['trainable_parameters'] = trainable_params
        results['parameter_efficiency'] = (trainable_params / total_params) * 100
        results['generation_times'] = generation_times
        results['avg_generation_time'] = np.mean(generation_times)
        results['std_generation_time'] = np.std(generation_times)
        results['avg_recipe_length'] = np.mean([len(p.split()) for p in predictions])

        # Memory usage
        if torch.cuda.is_available():
            results['memory_allocated_gb'] = torch.cuda.memory_allocated() / 1024**3
            results['memory_reserved_gb'] = torch.cuda.memory_reserved() / 1024**3
        else:
            results['memory_allocated_gb'] = 0
            results['memory_reserved_gb'] = 0

        return results

    def display_results(self, results):
        print("\nCHAPTER 4: EVALUATION RESULTS")
        print("=" * 60)
        print("\nTABLE 4.1: AUTOMATIC EVALUATION METRICS")
        print("-" * 60)
        print(f"{'Metric':<20} {'Mean':<12} {'Std Dev':<12}")
        print("-" * 60)
        print(f"{'BLEU Score':<20} {results['bleu_mean']:<12.4f} {results['bleu_std']:<12.4f}")
        print(f"{'ROUGE-1':<20} {results['rouge1_mean']:<12.4f} {results['rouge1_std']:<12.4f}")
        print(f"{'ROUGE-2':<20} {results['rouge2_mean']:<12.4f} {results['rouge2_std']:<12.4f}")
        print(f"{'ROUGE-L':<20} {results['rougeL_mean']:<12.4f} {results['rougeL_std']:<12.4f}")
        print(f"{'METEOR':<20} {results['meteor_mean']:<12.4f} {results['meteor_std']:<12.4f}")
        print(f"{'BERTScore F1':<20} {results['bertscore_mean']:<12.4f} {results['bertscore_std']:<12.4f}")
        print(f"{'Perplexity':<20} {results['perplexity_mean']:<12.2f} {results['perplexity_std']:<12.2f}")

        print("\n\nTABLE 4.2: TRAINING EFFICIENCY METRICS")
        print("-" * 60)
        print(f"{'Metric':<30} {'Value':<20}")
        print("-" * 60)
        print(f"{'Total Parameters':<30} {results['total_parameters']:,}")
        print(f"{'Trainable Parameters':<30} {results['trainable_parameters']:,}")
        print(f"{'Parameter Efficiency (%)':<30} {results['parameter_efficiency']:.2f}%")
        print(f"{'Memory Allocated (GB)':<30} {results['memory_allocated_gb']:.2f}")
        print(f"{'Avg Generation Time (s)':<30} {results['avg_generation_time']:.3f}")
        print(f"{'Avg Recipe Length (words)':<30} {results['avg_recipe_length']:.1f}")

        print("\n" + "=" * 60)

    def create_visualizations(self, results, predictions):
        import matplotlib.pyplot as plt, seaborn as sns, numpy as np
        sns.set_style("whitegrid")

        fig = plt.figure(figsize=(16, 12))
        ax1 = plt.subplot(3, 3, 1)
        metrics = ['BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR']
        values = [results['bleu_mean'], results['rouge1_mean'],
                  results['rouge2_mean'], results['rougeL_mean'], results['meteor_mean']]
        ax1.bar(metrics, values, alpha=0.7)
        ax1.set_ylim(0, 1)
        ax1.set_title('Figure 4.1: Automatic Metrics Comparison')

        ax2 = plt.subplot(3, 3, 2)
        metric_data = [results['bleu_scores'], results['rouge1_scores'],
                       results['rouge2_scores'], results['rougeL_scores'],
                       results['meteor_scores']]
        bp = ax2.boxplot(metric_data, labels=['BLEU', 'R-1', 'R-2', 'R-L', 'MET'], patch_artist=True)
        ax2.set_title('Figure 4.2: Metrics Distribution')

        ax3 = plt.subplot(3, 3, 3)
        trainable = results['trainable_parameters']
        frozen = results['total_parameters'] - trainable
        ax3.pie([trainable, frozen], labels=['Trainable', 'Frozen'], autopct='%1.1f%%', startangle=90)
        ax3.set_title('Figure 4.3: Parameter Efficiency')

        ax4 = plt.subplot(3, 3, 4)
        ax4.plot(results['generation_times'], 'o-')
        ax4.axhline(y=results['avg_generation_time'], color='r', linestyle='--')
        ax4.set_title('Figure 4.4: Generation Time per Recipe')

        ax5 = plt.subplot(3, 3, 5)
        ax5.hist(results['perplexity_scores'], bins=8, edgecolor='black', alpha=0.7)
        ax5.set_title('Figure 4.5: Perplexity Distribution')

        ax6 = plt.subplot(3, 3, 6)
        recipe_lengths = [len(p.split()) for p in predictions]
        ax6.hist(recipe_lengths, bins=8, edgecolor='black', alpha=0.7)
        ax6.set_title('Figure 4.6: Generated Recipe Length')

        ax7 = plt.subplot(3, 3, 7)
        metrics_matrix = np.array([results['bleu_scores'], results['rouge1_scores'],
                                   results['rouge2_scores'], results['rougeL_scores'],
                                   results['meteor_scores']])
        im = ax7.imshow(metrics_matrix, aspect='auto')
        ax7.set_yticks(range(5)); ax7.set_yticklabels(['BLEU','ROUGE-1','ROUGE-2','ROUGE-L','METEOR'])
        ax7.set_title('Figure 4.7: Metrics Heatmap per Recipe')
        plt.colorbar(im, ax=ax7)

        ax8 = plt.subplot(3, 3, 8)
        memory_data = [results['memory_allocated_gb'], results['memory_reserved_gb']]
        ax8.bar(['Allocated','Reserved'], memory_data, alpha=0.7)
        ax8.set_title('Figure 4.8: GPU Memory Usage')

        ax9 = plt.subplot(3, 3, 9)
        ax9.axis('off')
        summary_text = f"Best Metric: ROUGE-L ({results['rougeL_mean']:.4f})\nLowest Perplexity: {min(results['perplexity_scores']):.2f}\nFastest Generation: {min(results['generation_times']):.3f}s\nTrainable Params: {results['parameter_efficiency']:.2f}%\nAvg Gen Time: {results['avg_generation_time']:.3f}s\nMemory: {results['memory_allocated_gb']:.2f} GB"
        ax9.text(0.1, 0.5, summary_text, fontsize=10, family='monospace')
        ax9.set_title('Table 4.3: Performance Summary')

        plt.tight_layout()
        plt.savefig('chapter4_evaluation_results.png', dpi=300, bbox_inches='tight')
        plt.show()
        print("\nVisualization saved as 'chapter4_evaluation_results.png'")

# Run evaluator
evaluator = Chapter4Evaluator(model, tokenizer)
evaluation_results = evaluator.run_complete_evaluation()

print("\nChapter 4 Results Package Complete!")
print("Files generated:")
print("- training_loss_curves.png")
print("- chapter4_evaluation_results.png")
print("- figure_4_1_metrics_comparison.png (saved in evaluator.save_individual_figures)")

# ================================
# CELL 8: GRADIO WEB INTERFACE
# ================================
import gradio as gr

def gradio_generate_recipe(dish_name, about="", ingredients=""):
    try:
        recipe = generate_recipe(dish_name, about, ingredients)
        return recipe
    except Exception as e:
        return f"Error: {str(e)}"

with gr.Blocks() as demo:
    gr.Markdown("## 🍲 African Recipe Generator — Gemma-3 (1B) Adapter Fine-tuned")
    gr.Markdown("Generate authentic African recipes with your adapter fine-tuned Gemma-3 (1B) model.")

    with gr.Row():
        dish = gr.Textbox(label="Dish Name", placeholder="Egusi Soup")
    with gr.Row():
        about = gr.Textbox(label="About the Dish", placeholder="Traditional Nigerian soup")
    with gr.Row():
        ingredients = gr.Textbox(label="Ingredients", placeholder="Melon seeds, spinach")

    output = gr.Textbox(label="Generated Recipe")
    generate_btn = gr.Button("Generate Recipe")
    generate_btn.click(fn=gradio_generate_recipe, inputs=[dish, about, ingredients], outputs=output)

demo.launch(share=True)