# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWzHA-R3D27qNs1xfHIzUeRPIczEG3ry
"""

!pip install -q unsloth datasets accelerate bitsandbytes trl transformers peft pandas openpyxl rouge-score nltk textstat ipywidgets seaborn
!python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet')"

# Enable widget extension in Colab
try:
    import google.colab
    from google.colab import output
    output.enable_custom_widget_manager()
except Exception:
    pass

print("✅ All dependencies installed successfully!")

from google.colab import drive
import pandas as pd
import io
from google.colab import files

# Upload dataset
print('📤 Please upload your CSV dataset.')
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[file_name]))
print(f"✅ Loaded dataset: {file_name} — {len(df)} rows")
print(f"Columns: {list(df.columns)}")

import re
from html import unescape
import unicodedata

def clean_dataset(df):
    print("🧹 Cleaning dataset...")

    def clean_text(text):
        if pd.isna(text):
            return ""
        text = str(text)
        text = unescape(text)
        text = unicodedata.normalize('NFKD', text)
        text = text.replace('½', '1/2').replace('¼', '1/4').replace('¾', '3/4')
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    df = df.copy()
    for col in df.columns:
        df[col] = df[col].apply(clean_text)

    possible_name_cols = [c for c in df.columns if any(name in c.lower() for name in ['dish-name', 'dish_name', 'dish', 'name', 'title', 'recipe'])]
    possible_instr_cols = [c for c in df.columns if any(instr in c.lower() for instr in ['instructions', 'instruction', 'steps', 'method', 'directions', 'preparation'])]

    if not possible_name_cols:
        raise ValueError('Could not find dish name column')
    if not possible_instr_cols:
        raise ValueError('Could not find instructions column')

    name_col = possible_name_cols[0]
    instr_col = possible_instr_cols[0]

    initial_count = len(df)
    df = df.dropna(subset=[name_col, instr_col])
    df = df[df[instr_col].str.len() > 50]
    df = df[df[name_col].str.len() > 2]
    df = df.drop_duplicates(subset=[name_col])
    print(f"📊 Filtered from {initial_count} to {len(df)} recipes")

    def clean_instructions(instructions):
        instructions = re.sub(r'STEP\s*(\d+)', r'Step \1:', instructions, flags=re.IGNORECASE)
        instructions = re.sub(r'Step\s*(\d+)(?!:)', r'Step \1:', instructions, flags=re.IGNORECASE)
        instructions = re.sub(r'(\d+)\.', r'Step \1:', instructions)

        sentences = re.split(r'(?<=[.!?])\s+', instructions)
        cleaned_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if len(sentence) > 200:
                parts = re.split(r'\s+(and then|then|meanwhile|after that|next|finally|lastly)\s+', sentence, flags=re.IGNORECASE)
                for part in parts:
                    part = part.strip()
                    if len(part) > 10:
                        cleaned_sentences.append(part)
            elif len(sentence) > 10:
                cleaned_sentences.append(sentence)
        cleaned = '. '.join(s.rstrip('.').strip() for s in cleaned_sentences if s.strip())
        if cleaned and not cleaned.endswith(('.', '!', '?')):
            cleaned += '.'
        return cleaned

    df[instr_col] = df[instr_col].apply(clean_instructions)

    formatted_data = []
    for _, row in df.iterrows():
        dish_name = row[name_col]
        instruction = f"Generate a complete recipe for {dish_name}."

        about_cols = [c for c in df.columns if any(about in c.lower() for about in ['about', 'description', 'origin', 'type'])]
        if about_cols and pd.notna(row[about_cols[0]]) and row[about_cols[0]].strip():
            instruction += f"\nAbout: {row[about_cols[0]][:200]}"

        ing_cols = [c for c in df.columns if any(ing in c.lower() for ing in ['ingredients', 'ingredient', 'ings', 'items'])]
        if ing_cols and pd.notna(row[ing_cols[0]]) and row[ing_cols[0]].strip():
            instruction += f"\nIngredients: {row[ing_cols[0]][:400]}"

        cuisine_cols = [c for c in df.columns if any(cuisine in c.lower() for cuisine in ['cuisine', 'category', 'region', 'country'])]
        if cuisine_cols and pd.notna(row[cuisine_cols[0]]) and row[cuisine_cols[0]].strip():
            instruction += f"\nCuisine: {row[cuisine_cols[0]][:100]}"

        response = f"# {dish_name}\n\n"
        if ing_cols and pd.notna(row[ing_cols[0]]):
            response += f"**Ingredients:**\n{row[ing_cols[0]]}\n\n"
        response += f"**Instructions:**\n{row[instr_col]}"

        formatted_text = (
            "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n" +
            instruction +
            "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n" +
            response +
            "<|eot_id|>"
        )
        formatted_data.append({'text': formatted_text})

    result_df = pd.DataFrame(formatted_data)
    print(f"✅ Created {len(result_df)} formatted training examples")
    return result_df

# Clean dataset
cleaned_df = clean_dataset(df)
cleaned_df.to_csv('/content/llama3_cleaned_recipes.csv', index=False)
print('💾 Saved cleaned dataset to /content/llama3_cleaned_recipes.csv')

# Display a sample
print(cleaned_df['text'].iloc[0][:300] + "...")

import torch
from unsloth import FastLanguageModel
from datasets import Dataset

# Check device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"🖥️ Using device: {device}")
if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

# Load Llama 3 8B (4-bit)
model_name = "unsloth/llama-3-8b-bnb-4bit"
print(f"🤖 Loading {model_name}... (may take several minutes)")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_name,
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True
)

# Set pad token if missing
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    print("✅ Pad token set to EOS token")

# Apply LoRA
print("🔧 Applying LoRA configuration...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

# Prepare model for training
FastLanguageModel.for_training(model)
print("📊 Model ready for training")
model.print_trainable_parameters()

from trl import SFTTrainer, SFTConfig
from transformers import TrainerCallback
import time

class MetricsCallback(TrainerCallback):
    def __init__(self):
        super().__init__()
        self.training_loss = []
        self.steps = []
        self.epoch_loss = []
        self.epochs = []
        self.learning_rates = []
        self.start_time = time.time()
        self.step_times = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            if 'loss' in logs:
                self.training_loss.append(logs['loss'])
                self.steps.append(state.global_step)
                self.step_times.append(time.time() - self.start_time)
            if 'learning_rate' in logs:
                self.learning_rates.append(logs['learning_rate'])
            if state.global_step % 50 == 0 and 'loss' in logs:
                elapsed = time.time() - self.start_time
                print(f"Step {state.global_step}: Loss = {logs['loss']:.4f}, Time = {elapsed:.1f}s")

    def on_epoch_end(self, args, state, control, **kwargs):
        if self.training_loss:
            steps_per_epoch = max(1, len(self.training_loss) // max(1, int(state.num_train_epochs)))
            recent_losses = self.training_loss[-steps_per_epoch:]
            avg_loss = sum(recent_losses) / len(recent_losses) if recent_losses else 0
            self.epoch_loss.append(avg_loss)
            self.epochs.append(state.epoch)
            elapsed = time.time() - self.start_time
            print(f"\n🎯 Epoch {state.epoch} completed: Average Loss = {avg_loss:.4f}, Time = {elapsed/60:.1f} min")

callback = MetricsCallback()
train_dataset = Dataset.from_pandas(cleaned_df)

# Training configuration
training_args = SFTConfig(
    output_dir="./llama3_recipe_model",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=2e-4,
    num_train_epochs=3,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",
    optim="paged_adamw_32bit",
    gradient_checkpointing=True,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="no",
    seed=42
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    args=training_args,
    callbacks=[callback],
)


print("\n🚀 Starting training...")
start_time = time.time()
trainer.train()
training_time = time.time() - start_time

# Save model
trainer.save_model("./final_llama3_recipe_model")
tokenizer.save_pretrained("./final_llama3_recipe_model")
print(f"✅ Training completed in {training_time/60:.1f} min and model saved.")