# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaXKDlwSPd0WZ-NUlFHZJiTVtBpKIAwj
"""

!pip install -q unsloth datasets accelerate bitsandbytes trl transformers peft pandas openpyxl rouge-score nltk textstat
!python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet')"
print("✅ All packages installed!")

# CELL 2: Upload and Process Dataset
# ================================

from google.colab import files
import pandas as pd
import json
import re
from html import unescape

print("📁 Upload your African recipes dataset (CSV, JSON, XLSX)")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# Load dataset
if file_name.endswith('.csv'):
    df = pd.read_csv(file_name)
elif file_name.endswith('.json'):
    df = pd.read_json(file_name)
elif file_name.endswith(('.xlsx', '.xls')):
    df = pd.read_excel(file_name)

print(f"📊 Loaded {len(df)} recipes")

# Clean text
def clean_text(text):
    if pd.isna(text):
        return ""
    text = unescape(str(text))
    return re.sub(r'\s+', ' ', text).strip()

# Process dataset
for col in df.columns:
    df[col] = df[col].apply(clean_text)

df = df.dropna(subset=['Dish-Name', 'Instructions']).reset_index(drop=True)

# Format for training
formatted_data = []
for _, row in df.iterrows():
    instruction = f"Generate a complete recipe for {row['Dish-Name']}."
    if 'About' in row and row['About']:
        instruction += f"\nAbout: {row['About']}"
    if 'Ingredients' in row and row['Ingredients']:
        instruction += f"\nIngredients: {row['Ingredients']}"

    response = f"# {row['Dish-Name']}\n\n**Instructions:**\n{row['Instructions']}"

    formatted_data.append({
        'text': f"### Instruction:\n{instruction}\n\n### Response:\n{response}"
    })

dataset_df = pd.DataFrame(formatted_data)
print(f"✅ Processed {len(dataset_df)} recipes for training")

# CELL 3: Setup Gemma 3 Model
# ================================

import torch
from unsloth import FastLanguageModel
from datasets import Dataset

# Load Gemma 3 1B with QLoRA
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/gemma-3-1b-it-bnb-4bit",
    max_seq_length=1024,
    dtype=None,
    load_in_4bit=True,
)

# Apply LoRA
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules="all-linear",
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

FastLanguageModel.for_training(model)
print("✅ Model loaded with QLoRA")
model.print_trainable_parameters()

#CELL 4: Train Model
# ================================

from trl import SFTTrainer, SFTConfig

# Convert to dataset
train_dataset = Dataset.from_pandas(dataset_df)

# Train
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    args=SFTConfig(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        num_train_epochs=3,
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        optim="adamw_torch_fused",
        gradient_checkpointing=True,
        output_dir="./gemma3_african_recipes",
        logging_steps=10,
        save_strategy="epoch",
        max_seq_length=1024,
        dataset_text_field="text",
        seed=42,
    ),
)

print("🚀 Starting training...")
trainer.train()
trainer.save_model("./gemma3_african_recipes_final")
tokenizer.save_pretrained("./gemma3_african_recipes_final")
print("✅ Training completed!")

# CELL 5: Load Trained Model
# ================================

# Load trained model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="./gemma3_african_recipes_final",
    max_seq_length=1024,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)
print("✅ Trained model loaded for inference")

# More constrained generation
def generate_simple_recipe(dish_name):
    prompt = f"Recipe for {dish_name}:\n\nIngredients:\n-"

    inputs = tokenizer([prompt], return_tensors="pt", truncation=True, max_length=256)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.5,
        top_k=20,
        repetition_penalty=1.3,
        no_repeat_ngram_size=2,
        do_sample=True
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# ================================
# CELL 7: Interactive Generator
# ================================

import ipywidgets as widgets
from IPython.display import display, clear_output

def create_generator():
    dish_input = widgets.Text(
        value='Nigerian Suya',
        description='Dish:',
        layout=widgets.Layout(width='400px')
    )

    about_input = widgets.Textarea(
        value='Spicy grilled meat',
        description='About:',
        layout=widgets.Layout(width='400px', height='60px')
    )

    ingredients_input = widgets.Textarea(
        value='Beef, spices, onions',
        description='Ingredients:',
        layout=widgets.Layout(width='400px', height='80px')
    )

    generate_button = widgets.Button(
        description='Generate Recipe',
        button_style='success'
    )

    output = widgets.Output()

    def on_click(b):
        with output:
            clear_output(wait=True)
            dish = dish_input.value.strip()
            if dish:
                recipe = generate_african_recipe(
                    dish,
                    about_input.value.strip(),
                    ingredients_input.value.strip()
                )
                print(f"🍽️ {dish} Recipe:")
                print("=" * 50)
                print(recipe)

    generate_button.on_click(on_click)

    display(widgets.VBox([
        widgets.HTML("<h3>🍽️ African Recipe Generator</h3>"),
        dish_input,
        about_input,
        ingredients_input,
        generate_button,
        output
    ]))

create_generator()

# ================================
# CELL 8: Evaluation Metrics
# ================================

import numpy as np
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from nltk.tokenize import word_tokenize
import textstat
import time

class RecipeEvaluator:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.rouge_scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
        self.smoothing = SmoothingFunction()

    def calculate_metrics(self, predictions, references):
        # BLEU scores
        bleu_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=self.smoothing.method1)
            bleu_scores.append(score)

        # ROUGE scores
        rouge1_scores = []
        rouge2_scores = []
        rougeL_scores = []
        for pred, ref in zip(predictions, references):
            scores = self.rouge_scorer.score(ref, pred)
            rouge1_scores.append(scores['rouge1'].fmeasure)
            rouge2_scores.append(scores['rouge2'].fmeasure)
            rougeL_scores.append(scores['rougeL'].fmeasure)

        # METEOR scores
        meteor_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = meteor_score([ref_tokens], pred_tokens)
            meteor_scores.append(score)

        # Perplexity
        perplexities = []
        for text in predictions:
            inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
            with torch.no_grad():
                outputs = self.model(**inputs, labels=inputs["input_ids"])
                perplexity = torch.exp(outputs.loss).item()
                perplexities.append(min(perplexity, 1000))  # Cap at 1000

        return {
            'bleu_mean': np.mean(bleu_scores),
            'rouge1_mean': np.mean(rouge1_scores),
            'rouge2_mean': np.mean(rouge2_scores),
            'rougeL_mean': np.mean(rougeL_scores),
            'meteor_mean': np.mean(meteor_scores),
            'perplexity_mean': np.mean(perplexities)
        }

    def run_evaluation(self):
        print("🔬 Running Evaluation...")

        # Test dishes
        test_dishes = [
            {"name": "Jollof Rice", "about": "West African rice dish", "ingredients": "Rice, tomatoes, spices"},
            {"name": "Ugali", "about": "East African staple", "ingredients": "Cornmeal, water"},
            {"name": "Injera", "about": "Ethiopian bread", "ingredients": "Teff flour, water"},
            {"name": "Egusi Soup", "about": "Nigerian soup", "ingredients": "Melon seeds, spinach"},
            {"name": "Bobotie", "about": "South African dish", "ingredients": "Beef, curry, bread"}
        ]

        predictions = []
        references = []

        for dish in test_dishes:
            pred = generate_african_recipe(dish['name'], dish['about'], dish['ingredients'])
            predictions.append(pred)

            ref = f"{dish['name']} is a {dish['about']} made with {dish['ingredients']}"
            references.append(ref)

        results = self.calculate_metrics(predictions, references)

        # Model stats
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)

        print("\n📊 EVALUATION RESULTS")
        print("=" * 40)
        print(f"BLEU Score:      {results['bleu_mean']:.4f}")
        print(f"ROUGE-1:         {results['rouge1_mean']:.4f}")
        print(f"ROUGE-2:         {results['rouge2_mean']:.4f}")
        print(f"ROUGE-L:         {results['rougeL_mean']:.4f}")
        print(f"METEOR:          {results['meteor_mean']:.4f}")
        print(f"Perplexity:      {results['perplexity_mean']:.2f}")
        print(f"\nTotal Parameters:     {total_params:,}")
        print(f"Trainable Parameters: {trainable_params:,}")
        print(f"Parameter Efficiency: {(trainable_params/total_params)*100:.2f}%")

        return results

# Run evaluation
evaluator = RecipeEvaluator(model, tokenizer)
results = evaluator.run_evaluation()

print("\n🎉 Complete! Your African Recipe Generator is ready!")