# -*- coding: utf-8 -*-
"""QLORA LLAMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9zZIh6niCQH5eHnlcOy0v80-Fztg89V
"""

# Complete QLoRA Training with Unsloth - Llama 3.2 1B African Recipe Generator
# Uses 4-bit quantization for efficient training with Unsloth optimization

# ================================
# CELL 1: Install Unsloth and Dependencies
# ================================

!pip install -q unsloth
!pip uninstall -y unsloth -q
!pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q datasets accelerate trl pandas rouge-score nltk seaborn

# Download NLTK data
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# ================================
# CELL 2: Upload and Clean Dataset
# ================================

from google.colab import files
import pandas as pd
import re
from html import unescape
import unicodedata

# Upload dataset
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

def clean_dataset(df):
    def clean_text(text):
        if pd.isna(text):
            return ""
        text = str(text)
        text = unescape(text)
        text = unicodedata.normalize('NFKD', text)
        text = text.replace('½', '1/2').replace('¼', '1/4').replace('¾', '3/4')
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    # Clean all columns
    for col in df.columns:
        df[col] = df[col].apply(clean_text)

    # Remove invalid recipes
    df = df.dropna(subset=['Dish-Name', 'Instructions'])
    df = df[df['Instructions'].str.len() > 50]
    df = df[df['Dish-Name'].str.len() > 2]

    # Fix instructions formatting
    def clean_instructions(instructions):
        instructions = re.sub(r'STEP\s*(\d+)', r'Step \1:', instructions)
        instructions = re.sub(r'Step\s*(\d+)(?!:)', r'Step \1:', instructions)

        sentences = instructions.split('.')
        cleaned_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if len(sentence) > 150:
                parts = re.split(r'\s+(and then|then|meanwhile|after|next)\s+', sentence, flags=re.IGNORECASE)
                for part in parts:
                    if len(part.strip()) > 10:
                        cleaned_sentences.append(part.strip())
            elif len(sentence) > 10:
                cleaned_sentences.append(sentence)
        return '. '.join(cleaned_sentences) + '.'

    df['Instructions'] = df['Instructions'].apply(clean_instructions)

    # Format for training
    formatted_data = []
    for _, row in df.iterrows():
        instruction = f"Generate a complete recipe for {row['Dish-Name']}."
        if 'About' in row and row['About']:
            instruction += f"\nAbout: {row['About'][:200]}"
        if 'Ingredients' in row and row['Ingredients']:
            instruction += f"\nIngredients: {row['Ingredients'][:300]}"

        response = f"# {row['Dish-Name']}\n\n**Instructions:**\n{row['Instructions']}"

        formatted_data.append({
            'text': f"### Instruction:\n{instruction}\n\n### Response:\n{response}"
        })

    return pd.DataFrame(formatted_data)

cleaned_df = clean_dataset(df)
print(f"Processed {len(cleaned_df)} recipes")

# ================================
# CELL 3: Load Model with Unsloth QLoRA
# ================================

from unsloth import FastLanguageModel
from datasets import Dataset
import torch

# Model configuration
max_seq_length = 1024
dtype = None  # Auto-detect
load_in_4bit = True

print("Loading Llama 3.2 1B with Unsloth QLoRA...")

# Load model and tokenizer with Unsloth optimization
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

# Apply LoRA with Unsloth
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

# Prepare for training
FastLanguageModel.for_training(model)

# Print trainable parameters
model.print_trainable_parameters()

print("Model loaded successfully with Unsloth QLoRA!")

# ================================
# CELL 4: Train Model with Unsloth
# ================================

from trl import SFTTrainer, SFTConfig
from transformers.trainer_callback import TrainerCallback
import matplotlib.pyplot as plt

# Prepare dataset
train_dataset = Dataset.from_pandas(cleaned_df)

# Training callback for metrics
class MetricsCallback(TrainerCallback):
    def __init__(self):
        self.training_loss = []
        self.steps = []
        self.epoch_loss = []
        self.epochs = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and 'loss' in logs:
            self.training_loss.append(logs['loss'])
            self.steps.append(state.global_step)

    def on_epoch_end(self, args, state, control, **kwargs):
        if self.training_loss:
            avg_loss = sum(self.training_loss[-10:]) / min(10, len(self.training_loss))
            self.epoch_loss.append(avg_loss)
            self.epochs.append(state.epoch)

callback = MetricsCallback()

# Training configuration
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    max_seq_length=max_seq_length,
    dataset_text_field="text",
    args=SFTConfig(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        num_train_epochs=3,
        warmup_steps=10,
        lr_scheduler_type="linear",
        optim="adamw_8bit",
        weight_decay=0.01,
        logging_steps=50,
        save_strategy="epoch",
        output_dir="./llama3_recipe_qlora",
        seed=42,
        report_to="none",
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
    ),
    callbacks=[callback],
)

print("Starting training with Unsloth...")
trainer.train()

# Save model
model.save_pretrained("./final_llama3_recipe_qlora")
tokenizer.save_pretrained("./final_llama3_recipe_qlora")

# Plot training curves
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(callback.steps, callback.training_loss, 'b-', alpha=0.6, label='Training Loss')
plt.xlabel('Training Steps')
plt.ylabel('Loss')
plt.title('Training Loss Curve (Unsloth QLoRA)')
plt.grid(True, alpha=0.3)
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(callback.epochs, callback.epoch_loss, 'r-o', label='Epoch Loss')
plt.xlabel('Epoch')
plt.ylabel('Average Loss')
plt.title('Loss per Epoch')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.savefig('llama3_training_loss.png', dpi=300, bbox_inches='tight')
plt.show()

print("Training completed!")
if callback.training_loss:
    print(f"Final loss: {callback.training_loss[-1]:.4f}")
    print(f"Total steps: {callback.steps[-1]}")
print("Model saved to './final_llama3_recipe_qlora'")

# ================================
# CELL 5: Load Trained Model for Inference
# ================================

from unsloth import FastLanguageModel
import torch

print("Loading trained model...")

# Load model with Unsloth
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="./final_llama3_recipe_qlora",
    max_seq_length=1024,
    dtype=None,
    load_in_4bit=True,
)

# Enable inference mode
FastLanguageModel.for_inference(model)

def generate_recipe(dish_name, about="", ingredients=""):
    instruction = f"Generate a complete recipe for {dish_name}."
    if about:
        instruction += f"\nAbout: {about}"
    if ingredients:
        instruction += f"\nIngredients: {ingredients}"

    prompt = f"### Instruction:\n{instruction}\n\n### Response:\n"

    inputs = tokenizer([prompt], return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.7,
            top_p=0.9,
            top_k=50,
            repetition_penalty=1.1,
            do_sample=True,
            use_cache=True,
        )

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract response
    if "### Response:" in generated_text:
        response = generated_text.split("### Response:")[-1].strip()
    else:
        response = generated_text.strip()

    return response

# Test generation
print("\nTesting model generation...")
print("=" * 60)
test_recipe = generate_recipe("Jollof Rice", "West African rice dish", "Rice, tomatoes, spices")
print(test_recipe)
print("=" * 60)

# ================================
# CELL 6: Interactive Generator
# ================================

import ipywidgets as widgets
from IPython.display import display, clear_output

dish_input = widgets.Text(value='Egusi Soup', description='Dish:')
about_input = widgets.Textarea(value='Nigerian soup', description='About:')
ingredients_input = widgets.Textarea(value='Melon seeds, spinach', description='Ingredients:')
generate_button = widgets.Button(description='Generate Recipe', button_style='success')
output = widgets.Output()

def on_click(b):
    with output:
        clear_output(wait=True)
        print(f"Generating recipe for {dish_input.value}...")
        recipe = generate_recipe(dish_input.value, about_input.value, ingredients_input.value)
        print("\n" + "=" * 60)
        print(recipe)
        print("=" * 60)

generate_button.on_click(on_click)
display(widgets.VBox([dish_input, about_input, ingredients_input, generate_button, output]))

# ================================
# CELL 7: Complete Evaluation
# ================================

import subprocess
import sys

# Install rouge-score if needed
try:
    from rouge_score import rouge_scorer
except ModuleNotFoundError:
    print("Installing rouge-score...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "rouge-score"])
    from rouge_score import rouge_scorer

import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt
import seaborn as sns
import time

class Chapter4Evaluator:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.rouge_scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
        self.smoothing = SmoothingFunction()

    def run_complete_evaluation(self):
        print("Running Complete Evaluation (Unsloth QLoRA)...")
        print("=" * 60)

        # Test recipes
        test_dishes = [
            {"name": "Jollof Rice", "about": "West African rice", "ingredients": "Rice, tomatoes"},
            {"name": "Egusi Soup", "about": "Nigerian soup", "ingredients": "Melon seeds, spinach"},
            {"name": "Moi-Moi", "about": "Bean pudding", "ingredients": "Black-eyed peas"},
            {"name": "Ugali", "about": "East African staple", "ingredients": "Cornmeal, water"},
            {"name": "Suya", "about": "Grilled meat", "ingredients": "Beef, spices"},
            {"name": "Fufu", "about": "Starchy side dish", "ingredients": "Cassava"},
            {"name": "Injera", "about": "Ethiopian bread", "ingredients": "Teff flour"},
            {"name": "Pounded Yam", "about": "Nigerian staple", "ingredients": "Yam"}
        ]

        predictions = []
        references = []
        generation_times = []

        print("\nGenerating recipes for evaluation...")
        for dish in test_dishes:
            start_time = time.time()
            pred = generate_recipe(dish['name'], dish['about'], dish['ingredients'])
            gen_time = time.time() - start_time

            predictions.append(pred)
            generation_times.append(gen_time)

            ref = f"{dish['name']} is {dish['about']} made with {dish['ingredients']}. Prepare ingredients. Cook according to traditional method. Serve hot."
            references.append(ref)

            print(f"✓ Generated {dish['name']} ({gen_time:.2f}s)")

        # Calculate metrics
        results = self.calculate_metrics(predictions, references, generation_times)
        self.display_results(results)
        self.create_visualizations(results, predictions)

        return results

    def calculate_metrics(self, predictions, references, generation_times):
        results = {}

        # BLEU scores
        bleu_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=self.smoothing.method1)
            bleu_scores.append(score)

        results['bleu_scores'] = bleu_scores
        results['bleu_mean'] = np.mean(bleu_scores)
        results['bleu_std'] = np.std(bleu_scores)

        # ROUGE scores
        rouge1_scores, rouge2_scores, rougeL_scores = [], [], []
        for pred, ref in zip(predictions, references):
            scores = self.rouge_scorer.score(ref, pred)
            rouge1_scores.append(scores['rouge1'].fmeasure)
            rouge2_scores.append(scores['rouge2'].fmeasure)
            rougeL_scores.append(scores['rougeL'].fmeasure)

        results['rouge1_scores'] = rouge1_scores
        results['rouge1_mean'] = np.mean(rouge1_scores)
        results['rouge1_std'] = np.std(rouge1_scores)

        results['rouge2_scores'] = rouge2_scores
        results['rouge2_mean'] = np.mean(rouge2_scores)
        results['rouge2_std'] = np.std(rouge2_scores)

        results['rougeL_scores'] = rougeL_scores
        results['rougeL_mean'] = np.mean(rougeL_scores)
        results['rougeL_std'] = np.std(rougeL_scores)

        # METEOR scores
        meteor_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = meteor_score([ref_tokens], pred_tokens)
            meteor_scores.append(score)

        results['meteor_scores'] = meteor_scores
        results['meteor_mean'] = np.mean(meteor_scores)
        results['meteor_std'] = np.std(meteor_scores)

        # Perplexity
        perplexities = []
        for text in predictions:
            inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
            inputs = {k: v.to(self.model.device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = self.model(**inputs, labels=inputs["input_ids"])
                perplexity = torch.exp(outputs.loss).item()
                perplexities.append(min(perplexity, 1000))

        results['perplexity_scores'] = perplexities
        results['perplexity_mean'] = np.mean(perplexities)
        results['perplexity_std'] = np.std(perplexities)

        # Model efficiency
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)

        results['total_parameters'] = total_params
        results['trainable_parameters'] = trainable_params
        results['parameter_efficiency'] = (trainable_params / total_params) * 100

        # Generation metrics
        results['generation_times'] = generation_times
        results['avg_generation_time'] = np.mean(generation_times)
        results['std_generation_time'] = np.std(generation_times)

        # Memory usage
        if torch.cuda.is_available():
            results['memory_allocated_gb'] = torch.cuda.memory_allocated() / 1024**3
            results['memory_reserved_gb'] = torch.cuda.memory_reserved() / 1024**3
        else:
            results['memory_allocated_gb'] = 0
            results['memory_reserved_gb'] = 0

        # Recipe quality
        results['avg_recipe_length'] = np.mean([len(pred.split()) for pred in predictions])

        return results

    def display_results(self, results):
        print("\n" + "=" * 60)
        print("CHAPTER 4: EVALUATION RESULTS (Unsloth QLoRA)")
        print("=" * 60)

        print("\nTABLE 4.1: AUTOMATIC EVALUATION METRICS")
        print("-" * 60)
        print(f"{'Metric':<20} {'Mean':<12} {'Std Dev':<12}")
        print("-" * 60)
        print(f"{'BLEU Score':<20} {results['bleu_mean']:<12.4f} {results['bleu_std']:<12.4f}")
        print(f"{'ROUGE-1':<20} {results['rouge1_mean']:<12.4f} {results['rouge1_std']:<12.4f}")
        print(f"{'ROUGE-2':<20} {results['rouge2_mean']:<12.4f} {results['rouge2_std']:<12.4f}")
        print(f"{'ROUGE-L':<20} {results['rougeL_mean']:<12.4f} {results['rougeL_std']:<12.4f}")
        print(f"{'METEOR':<20} {results['meteor_mean']:<12.4f} {results['meteor_std']:<12.4f}")
        print(f"{'Perplexity':<20} {results['perplexity_mean']:<12.2f} {results['perplexity_std']:<12.2f}")

        print("\n\nTABLE 4.2: TRAINING EFFICIENCY METRICS")
        print("-" * 60)
        print(f"{'Metric':<30} {'Value':<20}")
        print("-" * 60)
        print(f"{'Total Parameters':<30} {results['total_parameters']:,}")
        print(f"{'Trainable Parameters':<30} {results['trainable_parameters']:,}")
        print(f"{'Parameter Efficiency (%)':<30} {results['parameter_efficiency']:.2f}%")
        print(f"{'Memory Allocated (GB)':<30} {results['memory_allocated_gb']:.2f}")
        print(f"{'Avg Generation Time (s)':<30} {results['avg_generation_time']:.3f}")
        print(f"{'Avg Recipe Length (words)':<30} {results['avg_recipe_length']:.1f}")
        print("=" * 60)

    def create_visualizations(self, results, predictions):
        sns.set_style("whitegrid")
        fig = plt.figure(figsize=(16, 12))

        # 1. Metrics Comparison
        ax1 = plt.subplot(3, 3, 1)
        metrics = ['BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR']
        values = [results['bleu_mean'], results['rouge1_mean'],
                 results['rouge2_mean'], results['rougeL_mean'], results['meteor_mean']]
        colors = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6']
        ax1.bar(metrics, values, color=colors, alpha=0.7)
        ax1.set_ylabel('Score')
        ax1.set_title('Automatic Metrics (Unsloth QLoRA)')
        ax1.set_ylim(0, 1)
        for i, v in enumerate(values):
            ax1.text(i, v + 0.02, f'{v:.3f}', ha='center', fontsize=9)

        # 2. Metrics Distribution
        ax2 = plt.subplot(3, 3, 2)
        metric_data = [results['bleu_scores'], results['rouge1_scores'],
                       results['rouge2_scores'], results['rougeL_scores'],
                       results['meteor_scores']]
        bp = ax2.boxplot(metric_data, labels=['BLEU', 'R-1', 'R-2', 'R-L', 'MET'], patch_artist=True)
        for patch, color in zip(bp['boxes'], colors):
            patch.set_facecolor(color)
            patch.set_alpha(0.6)
        ax2.set_ylabel('Score')
        ax2.set_title('Metrics Distribution')
        ax2.grid(True, alpha=0.3)

        # 3. Parameter Efficiency
        ax3 = plt.subplot(3, 3, 3)
        trainable = results['trainable_parameters']
        frozen = results['total_parameters'] - trainable
        ax3.pie([trainable, frozen], labels=['Trainable', 'Frozen'],
               colors=['#2ecc71', '#95a5a6'], autopct='%1.1f%%', startangle=90)
        ax3.set_title('Parameter Efficiency')

        # 4. Generation Time
        ax4 = plt.subplot(3, 3, 4)
        ax4.plot(results['generation_times'], 'o-', color='#3498db', linewidth=2, markersize=8)
        ax4.axhline(y=results['avg_generation_time'], color='r', linestyle='--',
                   label=f'Mean: {results["avg_generation_time"]:.3f}s')
        ax4.set_xlabel('Recipe Sample')
        ax4.set_ylabel('Time (seconds)')
        ax4.set_title('Generation Time per Recipe')
        ax4.legend()
        ax4.grid(True, alpha=0.3)

        # 5. Perplexity
        ax5 = plt.subplot(3, 3, 5)
        ax5.hist(results['perplexity_scores'], bins=8, color='#e74c3c', alpha=0.7, edgecolor='black')
        ax5.axvline(x=results['perplexity_mean'], color='blue', linestyle='--',
                   linewidth=2, label=f'Mean: {results["perplexity_mean"]:.2f}')
        ax5.set_xlabel('Perplexity')
        ax5.set_ylabel('Frequency')
        ax5.set_title('Perplexity Distribution')
        ax5.legend()

        # 6. Recipe Length
        ax6 = plt.subplot(3, 3, 6)
        recipe_lengths = [len(pred.split()) for pred in predictions]
        ax6.hist(recipe_lengths, bins=8, color='#9b59b6', alpha=0.7, edgecolor='black')
        ax6.axvline(x=np.mean(recipe_lengths), color='red', linestyle='--',
                   linewidth=2, label=f'Mean: {np.mean(recipe_lengths):.1f}')
        ax6.set_xlabel('Words')
        ax6.set_ylabel('Frequency')
        ax6.set_title('Generated Recipe Length')
        ax6.legend()

        # 7. Metrics Heatmap
        ax7 = plt.subplot(3, 3, 7)
        metrics_matrix = np.array([results['bleu_scores'], results['rouge1_scores'],
                                   results['rouge2_scores'], results['rougeL_scores'],
                                   results['meteor_scores']])
        im = ax7.imshow(metrics_matrix, cmap='YlOrRd', aspect='auto')
        ax7.set_yticks(range(5))
        ax7.set_yticklabels(['BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR'])
        ax7.set_xticks(range(len(predictions)))
        ax7.set_xticklabels([f'R{i+1}' for i in range(len(predictions))], fontsize=8)
        ax7.set_title('Metrics Heatmap per Recipe')
        plt.colorbar(im, ax=ax7)

        # 8. Memory Usage
        ax8 = plt.subplot(3, 3, 8)
        memory_data = [results['memory_allocated_gb'], results['memory_reserved_gb']]
        ax8.bar(['Allocated', 'Reserved'], memory_data, color=['#3498db', '#95a5a6'], alpha=0.7)
        ax8.set_ylabel('Memory (GB)')
        ax8.set_title('GPU Memory Usage')
        for i, v in enumerate(memory_data):
            ax8.text(i, v + 0.05, f'{v:.2f} GB', ha='center')

        # 9. Summary
        ax9 = plt.subplot(3, 3, 9)
        ax9.axis('off')
        summary_text = f"""
        Unsloth QLoRA Performance

        Best Metric: ROUGE-L ({results['rougeL_mean']:.4f})
        Lowest Perplexity: {min(results['perplexity_scores']):.2f}
        Fastest Generation: {min(results['generation_times']):.3f}s

        Efficiency:
        - Trainable: {results['parameter_efficiency']:.2f}%
        - Avg Gen Time: {results['avg_generation_time']:.3f}s
        - Memory: {results['memory_allocated_gb']:.2f} GB
        """
        ax9.text(0.1, 0.5, summary_text, fontsize=10, family='monospace',
                verticalalignment='center')
        ax9.set_title('Performance Summary')

        plt.tight_layout()
        plt.savefig('llama3_evaluation_results.png', dpi=300, bbox_inches='tight')
        plt.show()

        print("\nVisualization saved as 'llama3_evaluation_results.png'")

# Run evaluation
evaluator = Chapter4Evaluator(model, tokenizer)
evaluation_results = evaluator.run_complete_evaluation()

print("\n" + "=" * 60)
print("Evaluation Complete!")
print("Files generated:")
print("- llama3_training_loss.png")
print("- llama3_evaluation_results.png")
print("=" * 60)

# CELL 7: Complete Evaluation
# ================================
import nltk

# Download required NLTK tokenizers
nltk.download("punkt_tab")

import subprocess
import sys

# Install rouge-score if needed
try:
    from rouge_score import rouge_scorer
except ModuleNotFoundError:
    print("Installing rouge-score...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "rouge-score"])
    from rouge_score import rouge_scorer

import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt
import seaborn as sns
import time

class Chapter4Evaluator:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.rouge_scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
        self.smoothing = SmoothingFunction()

    def run_complete_evaluation(self):
        print("Running Complete Evaluation (Unsloth QLoRA)...")
        print("=" * 60)

        # Test recipes
        test_dishes = [
            {"name": "Jollof Rice", "about": "West African rice", "ingredients": "Rice, tomatoes"},
            {"name": "Egusi Soup", "about": "Nigerian soup", "ingredients": "Melon seeds, spinach"},
            {"name": "Moi-Moi", "about": "Bean pudding", "ingredients": "Black-eyed peas"},
            {"name": "Ugali", "about": "East African staple", "ingredients": "Cornmeal, water"},
            {"name": "Suya", "about": "Grilled meat", "ingredients": "Beef, spices"},
            {"name": "Fufu", "about": "Starchy side dish", "ingredients": "Cassava"},
            {"name": "Injera", "about": "Ethiopian bread", "ingredients": "Teff flour"},
            {"name": "Pounded Yam", "about": "Nigerian staple", "ingredients": "Yam"}
        ]

        predictions = []
        references = []
        generation_times = []

        print("\nGenerating recipes for evaluation...")
        for dish in test_dishes:
            start_time = time.time()
            pred = generate_recipe(dish['name'], dish['about'], dish['ingredients'])
            gen_time = time.time() - start_time

            predictions.append(pred)
            generation_times.append(gen_time)

            ref = f"{dish['name']} is {dish['about']} made with {dish['ingredients']}. Prepare ingredients. Cook according to traditional method. Serve hot."
            references.append(ref)

            print(f"✓ Generated {dish['name']} ({gen_time:.2f}s)")

        # Calculate metrics
        results = self.calculate_metrics(predictions, references, generation_times)
        self.display_results(results)
        self.create_visualizations(results, predictions)

        return results

    def calculate_metrics(self, predictions, references, generation_times):
        results = {}

        # BLEU scores
        bleu_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=self.smoothing.method1)
            bleu_scores.append(score)

        results['bleu_scores'] = bleu_scores
        results['bleu_mean'] = np.mean(bleu_scores)
        results['bleu_std'] = np.std(bleu_scores)

        # ROUGE scores
        rouge1_scores, rouge2_scores, rougeL_scores = [], [], []
        for pred, ref in zip(predictions, references):
            scores = self.rouge_scorer.score(ref, pred)
            rouge1_scores.append(scores['rouge1'].fmeasure)
            rouge2_scores.append(scores['rouge2'].fmeasure)
            rougeL_scores.append(scores['rougeL'].fmeasure)

        results['rouge1_scores'] = rouge1_scores
        results['rouge1_mean'] = np.mean(rouge1_scores)
        results['rouge1_std'] = np.std(rouge1_scores)

        results['rouge2_scores'] = rouge2_scores
        results['rouge2_mean'] = np.mean(rouge2_scores)
        results['rouge2_std'] = np.std(rouge2_scores)

        results['rougeL_scores'] = rougeL_scores
        results['rougeL_mean'] = np.mean(rougeL_scores)
        results['rougeL_std'] = np.std(rougeL_scores)

        # METEOR scores
        meteor_scores = []
        for pred, ref in zip(predictions, references):
            pred_tokens = word_tokenize(pred.lower())
            ref_tokens = word_tokenize(ref.lower())
            score = meteor_score([ref_tokens], pred_tokens)
            meteor_scores.append(score)

        results['meteor_scores'] = meteor_scores
        results['meteor_mean'] = np.mean(meteor_scores)
        results['meteor_std'] = np.std(meteor_scores)

        # Perplexity
        perplexities = []
        for text in predictions:
            inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
            inputs = {k: v.to(self.model.device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = self.model(**inputs, labels=inputs["input_ids"])
                perplexity = torch.exp(outputs.loss).item()
                perplexities.append(min(perplexity, 1000))

        results['perplexity_scores'] = perplexities
        results['perplexity_mean'] = np.mean(perplexities)
        results['perplexity_std'] = np.std(perplexities)

        # Model efficiency
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)

        results['total_parameters'] = total_params
        results['trainable_parameters'] = trainable_params
        results['parameter_efficiency'] = (trainable_params / total_params) * 100

        # Generation metrics
        results['generation_times'] = generation_times
        results['avg_generation_time'] = np.mean(generation_times)
        results['std_generation_time'] = np.std(generation_times)

        # Memory usage
        if torch.cuda.is_available():
            results['memory_allocated_gb'] = torch.cuda.memory_allocated() / 1024**3
            results['memory_reserved_gb'] = torch.cuda.memory_reserved() / 1024**3
        else:
            results['memory_allocated_gb'] = 0
            results['memory_reserved_gb'] = 0

        # Recipe quality
        results['avg_recipe_length'] = np.mean([len(pred.split()) for pred in predictions])

        return results

    def display_results(self, results):
        print("\n" + "=" * 60)
        print("CHAPTER 4: EVALUATION RESULTS (Unsloth QLoRA)")
        print("=" * 60)

        print("\nTABLE 4.1: AUTOMATIC EVALUATION METRICS")
        print("-" * 60)
        print(f"{'Metric':<20} {'Mean':<12} {'Std Dev':<12}")
        print("-" * 60)
        print(f"{'BLEU Score':<20} {results['bleu_mean']:<12.4f} {results['bleu_std']:<12.4f}")
        print(f"{'ROUGE-1':<20} {results['rouge1_mean']:<12.4f} {results['rouge1_std']:<12.4f}")
        print(f"{'ROUGE-2':<20} {results['rouge2_mean']:<12.4f} {results['rouge2_std']:<12.4f}")
        print(f"{'ROUGE-L':<20} {results['rougeL_mean']:<12.4f} {results['rougeL_std']:<12.4f}")
        print(f"{'METEOR':<20} {results['meteor_mean']:<12.4f} {results['meteor_std']:<12.4f}")
        print(f"{'Perplexity':<20} {results['perplexity_mean']:<12.2f} {results['perplexity_std']:<12.2f}")

        print("\n\nTABLE 4.2: TRAINING EFFICIENCY METRICS")
        print("-" * 60)
        print(f"{'Metric':<30} {'Value':<20}")
        print("-" * 60)
        print(f"{'Total Parameters':<30} {results['total_parameters']:,}")
        print(f"{'Trainable Parameters':<30} {results['trainable_parameters']:,}")
        print(f"{'Parameter Efficiency (%)':<30} {results['parameter_efficiency']:.2f}%")
        print(f"{'Memory Allocated (GB)':<30} {results['memory_allocated_gb']:.2f}")
        print(f"{'Avg Generation Time (s)':<30} {results['avg_generation_time']:.3f}")
        print(f"{'Avg Recipe Length (words)':<30} {results['avg_recipe_length']:.1f}")
        print("=" * 60)

    def create_visualizations(self, results, predictions):
        sns.set_style("whitegrid")
        fig = plt.figure(figsize=(16, 12))

        # 1. Metrics Comparison
        ax1 = plt.subplot(3, 3, 1)
        metrics = ['BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR']
        values = [results['bleu_mean'], results['rouge1_mean'],
                 results['rouge2_mean'], results['rougeL_mean'], results['meteor_mean']]
        colors = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6']
        ax1.bar(metrics, values, color=colors, alpha=0.7)
        ax1.set_ylabel('Score')
        ax1.set_title('Automatic Metrics (Unsloth QLoRA)')
        ax1.set_ylim(0, 1)
        for i, v in enumerate(values):
            ax1.text(i, v + 0.02, f'{v:.3f}', ha='center', fontsize=9)

        # 2. Metrics Distribution
        ax2 = plt.subplot(3, 3, 2)
        metric_data = [results['bleu_scores'], results['rouge1_scores'],
                       results['rouge2_scores'], results['rougeL_scores'],
                       results['meteor_scores']]
        bp = ax2.boxplot(metric_data, labels=['BLEU', 'R-1', 'R-2', 'R-L', 'MET'], patch_artist=True)
        for patch, color in zip(bp['boxes'], colors):
            patch.set_facecolor(color)
            patch.set_alpha(0.6)
        ax2.set_ylabel('Score')
        ax2.set_title('Metrics Distribution')
        ax2.grid(True, alpha=0.3)

        # 3. Parameter Efficiency
        ax3 = plt.subplot(3, 3, 3)
        trainable = results['trainable_parameters']
        frozen = results['total_parameters'] - trainable
        ax3.pie([trainable, frozen], labels=['Trainable', 'Frozen'],
               colors=['#2ecc71', '#95a5a6'], autopct='%1.1f%%', startangle=90)
        ax3.set_title('Parameter Efficiency')

        # 4. Generation Time
        ax4 = plt.subplot(3, 3, 4)
        ax4.plot(results['generation_times'], 'o-', color='#3498db', linewidth=2, markersize=8)
        ax4.axhline(y=results['avg_generation_time'], color='r', linestyle='--',
                   label=f'Mean: {results["avg_generation_time"]:.3f}s')
        ax4.set_xlabel('Recipe Sample')
        ax4.set_ylabel('Time (seconds)')
        ax4.set_title('Generation Time per Recipe')
        ax4.legend()
        ax4.grid(True, alpha=0.3)

        # 5. Perplexity
        ax5 = plt.subplot(3, 3, 5)
        ax5.hist(results['perplexity_scores'], bins=8, color='#e74c3c', alpha=0.7, edgecolor='black')
        ax5.axvline(x=results['perplexity_mean'], color='blue', linestyle='--',
                   linewidth=2, label=f'Mean: {results["perplexity_mean"]:.2f}')
        ax5.set_xlabel('Perplexity')
        ax5.set_ylabel('Frequency')
        ax5.set_title('Perplexity Distribution')
        ax5.legend()

        # 6. Recipe Length
        ax6 = plt.subplot(3, 3, 6)
        recipe_lengths = [len(pred.split()) for pred in predictions]
        ax6.hist(recipe_lengths, bins=8, color='#9b59b6', alpha=0.7, edgecolor='black')
        ax6.axvline(x=np.mean(recipe_lengths), color='red', linestyle='--',
                   linewidth=2, label=f'Mean: {np.mean(recipe_lengths):.1f}')
        ax6.set_xlabel('Words')
        ax6.set_ylabel('Frequency')
        ax6.set_title('Generated Recipe Length')
        ax6.legend()

        # 7. Metrics Heatmap
        ax7 = plt.subplot(3, 3, 7)
        metrics_matrix = np.array([results['bleu_scores'], results['rouge1_scores'],
                                   results['rouge2_scores'], results['rougeL_scores'],
                                   results['meteor_scores']])
        im = ax7.imshow(metrics_matrix, cmap='YlOrRd', aspect='auto')
        ax7.set_yticks(range(5))
        ax7.set_yticklabels(['BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR'])
        ax7.set_xticks(range(len(predictions)))
        ax7.set_xticklabels([f'R{i+1}' for i in range(len(predictions))], fontsize=8)
        ax7.set_title('Metrics Heatmap per Recipe')
        plt.colorbar(im, ax=ax7)

        # 8. Memory Usage
        ax8 = plt.subplot(3, 3, 8)
        memory_data = [results['memory_allocated_gb'], results['memory_reserved_gb']]
        ax8.bar(['Allocated', 'Reserved'], memory_data, color=['#3498db', '#95a5a6'], alpha=0.7)
        ax8.set_ylabel('Memory (GB)')
        ax8.set_title('GPU Memory Usage')
        for i, v in enumerate(memory_data):
            ax8.text(i, v + 0.05, f'{v:.2f} GB', ha='center')

        # 9. Summary
        ax9 = plt.subplot(3, 3, 9)
        ax9.axis('off')
        summary_text = f"""
        Unsloth QLoRA Performance

        Best Metric: ROUGE-L ({results['rougeL_mean']:.4f})
        Lowest Perplexity: {min(results['perplexity_scores']):.2f}
        Fastest Generation: {min(results['generation_times']):.3f}s

        Efficiency:
        - Trainable: {results['parameter_efficiency']:.2f}%
        - Avg Gen Time: {results['avg_generation_time']:.3f}s
        - Memory: {results['memory_allocated_gb']:.2f} GB
        """
        ax9.text(0.1, 0.5, summary_text, fontsize=10, family='monospace',
                verticalalignment='center')
        ax9.set_title('Performance Summary')

        plt.tight_layout()
        plt.savefig('llama3_evaluation_results.png', dpi=300, bbox_inches='tight')
        plt.show()

        print("\nVisualization saved as 'llama3_evaluation_results.png'")

# Run evaluation
evaluator = Chapter4Evaluator(model, tokenizer)
evaluation_results = evaluator.run_complete_evaluation()

print("\n" + "=" * 60)
print("Evaluation Complete!")
print("Files generated:")
print("- llama3_training_loss.png")
print("- llama3_evaluation_results.png")
print("=" * 60)

# Robust Gradio test UI for your local model (final_llama3_recipe_qlora)
# Paste and run this whole cell in the same runtime where your model exists.
!pip install -q gradio transformers unsloth torch

import os, traceback, sys
import gradio as gr
import torch

model_dir = "./final_llama3_recipe_qlora"   # adjust if needed (relative or absolute)
model_dir_abs = os.path.abspath(model_dir)
print("Using model path:", model_dir_abs)

# Holder variables
model = None
tokenizer = None
loader_used = None
load_error = None

# 1) If model/tokenizer already in memory (from earlier cells), use them
try:
    if 'model' in globals() and 'tokenizer' in globals() and model is not None and tokenizer is not None:
        print("Found in-memory model and tokenizer — using existing objects.")
        loader_used = "in-memory"
except Exception:
    pass

# 2) Try unsloth FastLanguageModel (if you used unsloth to train/save)
if loader_used is None:
    try:
        from unsloth import FastLanguageModel
        if os.path.isdir(model_dir_abs):
            print("Attempting to load using unsloth.FastLanguageModel.from_pretrained(...)")
            try:
                mdl, tok = FastLanguageModel.from_pretrained(model_name=model_dir_abs, max_seq_length=1024, load_in_4bit=True)
                FastLanguageModel.for_inference(mdl)
                model, tokenizer = mdl, tok
                loader_used = "unsloth"
                print("Loaded model with unsloth.")
            except Exception as e:
                print("unsloth load failed:", e)
        else:
            print("unsloth not used: model dir does not exist at path.")
    except Exception as e:
        # unsloth not installed or not appropriate
        print("unsloth not available or failed to import:", str(e))

# 3) Try Hugging Face transformers local load (absolute path, local_files_only)
if loader_used is None:
    try:
        from transformers import AutoTokenizer, AutoModelForCausalLM
        if not os.path.isdir(model_dir_abs):
            raise FileNotFoundError(f"Local model folder not found at {model_dir_abs}")
        print("Attempting to load with transformers AutoTokenizer / AutoModelForCausalLM (local_files_only=True)...")
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_dir_abs, local_files_only=True)
        except Exception as e:
            # try without local_files_only as a fallback (will try network)
            print("tokenizer local load failed:", e)
            tokenizer = AutoTokenizer.from_pretrained(model_dir_abs)
        try:
            model = AutoModelForCausalLM.from_pretrained(
                model_dir_abs,
                local_files_only=True,
                torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
                device_map="auto" if torch.cuda.is_available() else None,
            )
        except Exception as e:
            print("model local load failed, trying without local_files_only (may download):", e)
            model = AutoModelForCausalLM.from_pretrained(
                model_dir_abs,
                torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
                device_map="auto" if torch.cuda.is_available() else None,
            )
        loader_used = "transformers-local"
        print("Loaded model with transformers from local folder.")
    except Exception as e:
        load_error = traceback.format_exc()
        print("Transformers load failed:", e)

# 4) If still nothing, show friendly error
if loader_used is None:
    msg = f"""
No model loader succeeded.

Model folder checked: {model_dir_abs}

Last loader error (traceback):
{load_error}

Possible reasons:
 - model directory missing or not uploaded to runtime.
 - model not saved in HuggingFace format or saved with a custom toolkit (unsloth).
 - If you trained with unsloth, re-run the training cell (to keep objects in memory) or ensure the folder contains the expected files.

Options:
 - Upload your model folder to Colab / notebook storage and set model_dir to its path.
 - Or set use_api mode to call your deployed Fireworks.ai endpoint (I can give that snippet).
"""
    print(msg)
    # Launch a minimal UI that reports the error when pressing Generate
    def fail_gen(prompt, max_new_tokens=200, temperature=0.7, top_p=0.9):
        return msg

    with gr.Blocks() as demo_err:
        gr.Markdown("### Error: Model not loaded")
        gr.Textbox(label="Recipe Prompt", placeholder="Enter prompt")
        out = gr.Textbox(label="Result")
        btn = gr.Button("Generate (will show error)")
        btn.click(fn=fail_gen, inputs=[], outputs=out)
        demo_err.launch(share=True)
    raise RuntimeError("Model load failed; see printed message above.")

# --- define generation function depending on loader ---
def generate_with_loaded(prompt, max_new_tokens=300, temperature=0.7, top_p=0.9):
    try:
        # prepare prompt exactly as your training format (optional)
        if prompt.strip() == "":
            return "Please enter a recipe prompt (e.g., 'How to make Jollof Rice')"
        full_prompt = prompt if prompt.strip().startswith("### Instruction:") else f"### Instruction:\n{prompt}\n\n### Response:\n"

        # If model is unsloth type (FastLanguageModel)
        if loader_used == "unsloth" or (model.__class__.__module__.startswith("unsloth") if model is not None else False):
            inputs = tokenizer([full_prompt], return_tensors="pt", truncation=True, max_length=512)
            inputs = {k: v.to(next(model.parameters()).device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    temperature=temperature,
                    top_p=top_p,
                    do_sample=True,
                    pad_token_id=getattr(tokenizer, "eos_token_id", None) or tokenizer.pad_token_id
                )
            # unsloth generate may return different shapes
            try:
                input_len = inputs["input_ids"].shape[1]
                generated_tokens = outputs[0][input_len:]
            except Exception:
                generated_tokens = outputs[0]
            text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
            return text

        # Else assume transformers model
        else:
            device = model.device if hasattr(model, "device") else next(model.parameters()).device
            inputs = tokenizer(full_prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
            with torch.no_grad():
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    temperature=temperature,
                    top_p=top_p,
                    do_sample=True,
                    pad_token_id=tokenizer.eos_token_id if tokenizer.eos_token_id is not None else tokenizer.pad_token_id
                )
            return tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        return f"Generation error:\n{e}\n\n{traceback.format_exc()}"

# --- Build Gradio UI ---
with gr.Blocks() as demo:
    gr.Markdown("## 🍲 Test Your Fine-Tuned Recipe Model")
    gr.Markdown(f"**Loader used:** {loader_used}")

    prompt_input = gr.Textbox(label="Recipe Prompt", placeholder="e.g., Generate a complete recipe for Jollof Rice", lines=2)
    max_tokens = gr.Slider(50, 500, value=250, step=50, label="Max New Tokens")
    temperature = gr.Slider(0.1, 1.2, value=0.7, step=0.05, label="Temperature")
    top_p = gr.Slider(0.1, 1.0, value=0.9, step=0.05, label="Top-p")

    output_box = gr.Textbox(label="Generated Recipe", lines=18)
    gen_btn = gr.Button("Generate Recipe")
    gen_btn.click(fn=generate_with_loaded, inputs=[prompt_input, max_tokens, temperature, top_p], outputs=output_box)

print("Launching Gradio... (share=True for a public link)")
demo.launch(share=True)